In [1]:
import pandas as pd
import numpy as np

In [2]:
rand=np.random.RandomState(42)
x=rand.randint(100,size=10)
x

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [3]:
[x[1],x[3],x[0]]#making list of array elements

[92, 71, 51]

In [4]:
indeces=[1,3,0]
x[indeces]

array([92, 71, 51])

In [5]:
arr=[[2,7]
     ,[8,4]]

In [6]:
x[arr]#we can make 2d matrices from 1d matrices

array([[14, 86],
       [74, 60]])

### SORTING ARRAY

In [7]:
x=np.array([2,4,3,1,0])
a=np.sort(x)#does sort temporarily

In [8]:
x

array([2, 4, 3, 1, 0])

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
%timeit x.sort()

310 ns ± 39.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
x

array([0, 1, 2, 3, 4])

In [12]:
x=np.array([2,4,3,1,0])
np.argsort(x)#gives the index of original after sorting

array([4, 3, 0, 2, 1], dtype=int64)

In [13]:
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [14]:
np.sort(x)#sort the rows in the matrix

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [15]:
np.sort(x,axis=0)#sort the column in the matrix

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [16]:
x=np.array([7,2,3,1,6,5,4])
x

array([7, 2, 3, 1, 6, 5, 4])

In [17]:
np.partition(x,4)

array([2, 1, 3, 4, 5, 6, 7])

### WE USED PARTITION TO SPERATE FROM A SPECIFIC POINT TO FULLFILL THE SPECIFIC CODITION AROUND THE POINT.IT SEPERATES BIGGER AND SMALLER NUMBER FROM A SPECIIC POINT

In [18]:
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [19]:
np.partition(x,2)#all element to the right is bigger from point 4(index=3)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

In [20]:
ran=np.random.RandomState(43)
y=ran.randint(0,20,(4,4))
y

array([[ 4,  0, 17, 16],
       [19, 17,  2, 14],
       [ 0,  3, 18, 11],
       [ 1, 15,  2, 11]])

In [21]:
np.partition(y,2, axis=0)#Now it becomes row wise

array([[ 0,  0,  2, 11],
       [ 1,  3,  2, 11],
       [ 4, 15, 17, 14],
       [19, 17, 18, 16]])

### IT DOES NOT DO SORTING IN ANY WAY BUT CONCIDENCE CAN HAPPEN

### STRUCTURED DATA :NUMPY'S STRUCTURED ARRAYS

In [22]:
name=['Ram','Sam','Hemant','Raju']
age=[22,23,24,19]
wt=[50,60,55,63]
data=np.zeros(4,dtype={'names':('name','age','wt'),
                       'formats':('U10','i4','f8')})
data.dtype

dtype([('name', '<U10'), ('age', '<i4'), ('wt', '<f8')])

In [23]:
data['name']=name
data['age']=age
data['wt']=wt

In [24]:
data

array([('Ram', 22, 50.), ('Sam', 23, 60.), ('Hemant', 24, 55.),
       ('Raju', 19, 63.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('wt', '<f8')])

In [25]:
name=['Ram','Sam','Hemant','Raju']
caste=['bahadur','kc','bc','lc']
data=np.zeros(4,dtype={'names':('name','caste'),
                       'formats':('U10','U10')})
data['name']=name
data['caste']=caste
data

array([('Ram', 'bahadur'), ('Sam', 'kc'), ('Hemant', 'bc'),
       ('Raju', 'lc')], dtype=[('name', '<U10'), ('caste', '<U10')])

In [26]:
data['name']

array(['Ram', 'Sam', 'Hemant', 'Raju'], dtype='<U10')

In [27]:
data['caste']

array(['bahadur', 'kc', 'bc', 'lc'], dtype='<U10')

In [31]:
books=['Metamorphosis','God is dead','Republic']
authors=['Franz Kafka','Friedrich Nitzae','Plato']
data=np.zeros(3,dtype={'names':('books','authors')
                       ,'formats':('U10','U10')})
data['books']=books
data['authors']=authors
data

array([('Metamorpho', 'Franz Kafk'), ('God is dea', 'Friedrich '),
       ('Republic', 'Plato')],
      dtype=[('books', '<U10'), ('authors', '<U10')])

#### SERIES IS ONE DIMENSIONAL AND DATAFRAMES ARE MULTIDIMENSIONAL ARRAY WITH ROW AND COLUMN