In [2]:
import numpy as np
arr=np.array([[3,5]
      ,[4,7],
      [9,8]])
print(arr[2:3])

[[9 8]]


In [1]:
import numpy as np
arr = np.array([[3, 5], 
                [4, 7],
                [9, 8]])
print(arr[2:3])


[[9 8]]


## RESHAPE THE MATRIX IN NEEDED ORDER OR DIMENSION

In [8]:
arr=np.arange(1,7).reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

## CONTATINATION AND SPLITTING OF ARRAY

In [4]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [5]:
array2d=np.array([[1,2,3],[4,5,6]])

In [7]:
np.concatenate([array2d,array2d])#in default it adds to rows in 2d by  default ie axia=0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [9]:
array2d=np.array([[1,2,3],[4,5,6]])
np.concatenate([array2d,array2d],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [11]:
x=[1,2,3,4,5,6,7,8,9]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8 9]


In [12]:
x1,x2,x3=np.split(x,[4,8])
print(x1,x2,x3)


[1 2 3 4] [5 6 7 8] [9]


In [15]:
mt=np.arange(1,17).reshape(4,4)
print(mt)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
up,down=np.vsplit(mt,[2])
print(up)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
hs=np.arange(2,18).reshape(4,4)
left,right=np.hsplit(hs,[1])
print(right)


[[ 3  4  5]
 [ 7  8  9]
 [11 12 13]
 [15 16 17]]


In [29]:
import numpy as np
np.random.seed(0)
def rec(values):
    out=np.empty(len(values))
    for i in range(len(values)):
        output=1.0/values
        return output
values=np.random.randint(1,10,size=5)
rec(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [ ]:
big_array=np.random.randint(1,100,size=1000000)
