In [2]:
import numpy as np
np.random.rand(4)

array([0.00216463, 0.35320184, 0.61642014, 0.06850669])

## POSITIVE RANDOM ARRAY close to 0

In [4]:
np.random.random(4)

array([0.44622255, 0.98504259, 0.71048136, 0.48380048])

In [6]:
np.random.rand(2,5)#to make multiple variable

array([[0.03081205, 0.41687401, 0.80968082, 0.62237104, 0.52680229],
       [0.54579338, 0.79015471, 0.36177351, 0.7161187 , 0.29052466]])

In [7]:
np.random.random((2,5))#

array([[0.48167883, 0.01613847, 0.96450716, 0.1686269 , 0.25726687],
       [0.11115828, 0.22747579, 0.31139788, 0.38226044, 0.25114241]])

## NEGETIVE and positive RANDOM  close to 0

In [8]:
np.random.randn(2,2)#2d array of negetive value and postive

array([[-0.53356296,  2.21870911],
       [ 0.21498322, -1.42519112]])

### TO GIVE VALUE IN [0,1)

In [10]:
np.random.ranf((2,2))

array([[0.09691943, 0.57790403],
       [0.26053995, 0.64801455]])

## To make random value array in any range

In [15]:
np.random.randint(1,10,size=5)#(min,max,size)

array([3, 1, 9, 8, 4])

In [16]:
np.random.randint(1,20,size=(3,3))#(min,max,size)

array([[13,  1,  8],
       [ 4,  5,  8],
       [ 7,  4,  9]])